/*	A javascript toolset for helping work with Chinese characters in a web context or nodeJS.
 *
 * (The MIT License)
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the 'Software'), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * 這是一份MIT的非官方中文翻譯。它並非MIT發布，也不是使用MIT授權的軟件的法定發布條款——只有MIT授權的英文原版具
 * 有這樣的效力。然而，我們希望這份翻譯能夠幫助中文讀者更好的理解MIT授權。
 *
 * 現授予的權限，免費向任何人索取該軟件和相關的文檔文件（ “軟件” ），以處理軟件，沒有任何限制，包括但不限於使用權，複製，
 * 修改，合併，出版，發行，授權，和/或銷售軟件的副本，並允許的人提供的軟件是這樣做，但須符合下列條件：
 * 上述版權聲明和本許可聲明中應包括所有副本或實質性部分的軟件。
 * 該軟件是“按原樣”提供，不做任何保證，明示或暗示，包括但不限於適銷性，針對特定用途的適用性和非侵權的。
 * 在任何情況下，作者或版權持有人對任何索賠，損害賠償或其他責任，無論是在一項行動的合同，侵權或其他因出於或有關的軟件
 * 或利用等交易必須軟件。
 */

	/* A complete lookup reference from pinyin (with no tones) to zhuyin (also with no tones) */
	var __pinyinToZhuyinLookup = {
		a:'ㄚ',
		ai:'ㄞ',
		an:'ㄢ',
		ang:'ㄤ',
		ao:'ㄠ',
		ba:'ㄅㄚ',
		bai:'ㄅㄞ',
		ban:'ㄅㄢ',
		bang:'ㄅㄤ',
		bao:'ㄅㄠ',
		bei:'ㄅㄟ',
		ben:'ㄅㄣ',
		beng:'ㄅㄥ',
		bi:'ㄅㄧ',
		bian:'ㄅㄧㄢ',
		biao:'ㄅㄧㄠ',
		bie:'ㄅㄧㄝ',
		bin:'ㄅㄧㄣ',
		bing:'ㄅㄧㄥ',
		bo:'ㄅㄛ',
		bu:'ㄅㄨ',
		ca:'ㄘㄚ',
		cai:'ㄘㄞ',
		can:'ㄘㄢ',
		cang:'ㄘㄤ',
		cao:'ㄘㄠ',
		ce:'ㄘㄜ',
		cen:'ㄘㄣ',
		ceng:'ㄘㄥ',
		cha:'ㄔㄚ',
		chai:'ㄔㄞ',
		chan:'ㄔㄢ',
		chang:'ㄔㄤ',
		chao:'ㄔㄠ',
		che:'ㄔㄜ',
		chen:'ㄔㄣ',
		cheng:'ㄔㄥ',
		chi:'ㄔ',
		chong:'ㄔㄨㄥ',
		chou:'ㄔㄡ',
		chu:'ㄔㄨ',
		chua:'ㄔㄨㄚ',
		chuai:'ㄔㄨㄞ',
		chuan:'ㄔㄨㄢ',
		chuang:'ㄔㄨㄤ',
		chui:'ㄔㄨㄟ',
		chun:'ㄔㄨㄣ',
		chuo:'ㄔㄨㄛ',
		ci:'ㄘ',
		cong:'ㄘㄨㄥ',
		cou:'ㄘㄡ',
		cu:'ㄘㄨ',
		cuan:'ㄘㄨㄢ',
		cui:'ㄘㄨㄟ',
		cun:'ㄘㄨㄣ',
		cuo:'ㄘㄨㄛ',
		da:'ㄉㄚ',
		dai:'ㄉㄞ',
		dan:'ㄉㄢ',
		dang:'ㄉㄤ',
		dao:'ㄉㄠ',
		de:'ㄉㄜ',
		dei:'ㄉㄟ',
		den:'ㄉㄣ',
		deng:'ㄉㄥ',
		di:'ㄉㄧ',
		dia:'ㄉㄧㄚ',
		dian:'ㄉㄧㄢ',
		diao:'ㄉㄧㄠ',
		die:'ㄉㄧㄝ',
		ding:'ㄉㄧㄥ',
		diu:'ㄉㄧㄡ',
		dong:'ㄉㄨㄥ',
		dou:'ㄉㄡ',
		du:'ㄉㄨ',
		duan:'ㄉㄨㄢ',
		dui:'ㄉㄨㄟ',
		dun:'ㄉㄨㄣ',
		duo:'ㄉㄨㄛ',
		e:'ㄜ',
		ei:'ㄟ',
		en:'ㄣ',
		eng:'ㄥ',
		er:'ㄦ',
		fa:'ㄈㄚ',
		fan:'ㄈㄢ',
		fang:'ㄈㄤ',
		fei:'ㄈㄟ',
		fen:'ㄈㄣ',
		feng:'ㄈㄥ',
		fo:'ㄈㄛ',
		fou:'ㄈㄡ',
		fu:'ㄈㄨ',
		ga:'ㄍㄚ',
		gai:'ㄍㄞ',
		gan:'ㄍㄢ',
		gang:'ㄍㄤ',
		gao:'ㄍㄠ',
		ge:'ㄍㄜ',
		gei:'ㄍㄟ',
		gen:'ㄍㄣ',
		geng:'ㄍㄥ',
		gong:'ㄍㄨㄥ',
		gou:'ㄍㄡ',
		gu:'ㄍㄨ',
		gua:'ㄍㄨㄚ',
		guai:'ㄍㄨㄞ',
		guan:'ㄍㄨㄢ',
		guang:'ㄍㄨㄤ',
		gui:'ㄍㄨㄟ',
		gun:'ㄍㄨㄣ',
		guo:'ㄍㄨㄛ',
		ha:'ㄏㄚ',
		hai:'ㄏㄞ',
		han:'ㄏㄢ',
		hang:'ㄏㄤ',
		hao:'ㄏㄠ',
		he:'ㄏㄜ',
		hei:'ㄏㄟ',
		hen:'ㄏㄣ',
		heng:'ㄏㄥ',
		hong:'ㄏㄨㄥ',
		hou:'ㄏㄡ',
		hu:'ㄏㄨ',
		hua:'ㄏㄨㄚ',
		huai:'ㄏㄨㄞ',
		huan:'ㄏㄨㄢ',
		huang:'ㄏㄨㄤ',
		hui:'ㄏㄨㄟ',
		hun:'ㄏㄨㄣ',
		huo:'ㄏㄨㄛ',
		ji:'ㄐㄧ',
		jia:'ㄐㄧㄚ',
		jian:'ㄐㄧㄢ',
		jiang:'ㄐㄧㄤ',
		jiao:'ㄐㄧㄠ',
		jie:'ㄐㄧㄝ',
		jin:'ㄐㄧㄣ',
		jing:'ㄐㄧㄥ',
		jiong:'ㄐㄩㄥ',
		jiu:'ㄐㄧㄡ',
		ju:'ㄐㄩ',
		juan:'ㄐㄩㄢ',
		jue:'ㄐㄩㄝ',
		jun:'ㄐㄩㄣ',
		ka:'ㄎㄚ',
		kai:'ㄎㄞ',
		kan:'ㄎㄢ',
		kang:'ㄎㄤ',
		kao:'ㄎㄠ',
		ke:'ㄎㄜ',
		kei:'ㄎㄟ',
		ken:'ㄎㄣ',
		keng:'ㄎㄥ',
		kong:'ㄎㄨㄥ',
		kou:'ㄎㄡ',
		ku:'ㄎㄨ',
		kua:'ㄎㄨㄚ',
		kuai:'ㄎㄨㄞ',
		kuan:'ㄎㄨㄢ',
		kuang:'ㄎㄨㄤ',
		kui:'ㄎㄨㄟ',
		kun:'ㄎㄨㄣ',
		kuo:'ㄎㄨㄛ',
		la:'ㄌㄚ',
		lai:'ㄌㄞ',
		lan:'ㄌㄢ',
		lang:'ㄌㄤ',
		lao:'ㄌㄠ',
		le:'ㄌㄜ',
		lei:'ㄌㄟ',
		leng:'ㄌㄥ',
		li:'ㄌㄧ',
		lia:'ㄌㄧㄚ',
		lian:'ㄌㄧㄢ',
		liang:'ㄌㄧㄤ',
		liao:'ㄌㄧㄠ',
		lie:'ㄌㄧㄝ',
		lin:'ㄌㄧㄣ',
		ling:'ㄌㄧㄥ',
		liu:'ㄌㄧㄡ',
		long:'ㄌㄨㄥ',
		lou:'ㄌㄡ',
		lu:'ㄌㄨ',
		lü:'ㄌㄩ',
		luan:'ㄌㄨㄢ',
		lüe:'ㄌㄩㄝ',
		lun:'ㄌㄨㄣ',
		luo:'ㄌㄨㄛ',
		ma:'ㄇㄚ',
		mai:'ㄇㄞ',
		man:'ㄇㄢ',
		mang:'ㄇㄤ',
		mao:'ㄇㄠ',
		me:'ㄇㄜ',
		mei:'ㄇㄟ',
		men:'ㄇㄣ',
		meng:'ㄇㄥ',
		mi:'ㄇㄧ',
		mian:'ㄇㄧㄢ',
		miao:'ㄇㄧㄠ',
		mie:'ㄇㄧㄝ',
		min:'ㄇㄧㄣ',
		ming:'ㄇㄧㄥ',
		miu:'ㄇㄧㄡ',
		mo:'ㄇㄛ',
		mou:'ㄇㄡ',
		mu:'ㄇㄨ',
		na:'ㄋㄚ',
		nai:'ㄋㄞ',
		nan:'ㄋㄢ',
		nang:'ㄋㄤ',
		nao:'ㄋㄠ',
		ne:'ㄋㄜ',
		nei:'ㄋㄟ',
		nen:'ㄋㄣ',
		neng:'ㄋㄥ',
		ni:'ㄋㄧ',
		nian:'ㄋㄧㄢ',
		niang:'ㄋㄧㄤ',
		niao:'ㄋㄧㄠ',
		nie:'ㄋㄧㄝ',
		nin:'ㄋㄧㄣ',
		ning:'ㄋㄧㄥ',
		niu:'ㄋㄧㄡ',
		nong:'ㄋㄨㄥ',
		nou:'ㄋㄡ',
		nu:'ㄋㄨ',
		nü:'ㄋㄩ',
		nuan:'ㄋㄨㄢ',
		nüe:'ㄋㄩㄝ',
		nun:'ㄋㄨㄣ',
		nuo:'ㄋㄨㄛ',
		o:'ㄛ',
		ou:'ㄡ',
		pa:'ㄆㄚ',
		pai:'ㄆㄞ',
		pan:'ㄆㄢ',
		pang:'ㄆㄤ',
		pao:'ㄆㄠ',
		pei:'ㄆㄟ',
		pen:'ㄆㄣ',
		peng:'ㄆㄥ',
		pi:'ㄆㄧ',
		pian:'ㄆㄧㄢ',
		piao:'ㄆㄧㄠ',
		pie:'ㄆㄧㄝ',
		pin:'ㄆㄧㄣ',
		ping:'ㄆㄧㄥ',
		po:'ㄆㄛ',
		pou:'ㄆㄡ',
		pu:'ㄆㄨ',
		qi:'ㄑㄧ',
		qia:'ㄑㄧㄚ',
		qian:'ㄑㄧㄢ',
		qiang:'ㄑㄧㄤ',
		qiao:'ㄑㄧㄠ',
		qie:'ㄑㄧㄝ',
		qin:'ㄑㄧㄣ',
		qing:'ㄑㄧㄥ',
		qiong:'ㄑㄩㄥ',
		qiu:'ㄑㄧㄡ',
		qu:'ㄑㄩ',
		quan:'ㄑㄩㄢ',
		que:'ㄑㄩㄝ',
		qun:'ㄑㄩㄣ',
		ran:'ㄖㄢ',
		rang:'ㄖㄤ',
		rao:'ㄖㄠ',
		re:'ㄖㄜ',
		ren:'ㄖㄣ',
		reng:'ㄖㄥ',
		ri:'ㄖ',
		rong:'ㄖㄨㄥ',
		rou:'ㄖㄡ',
		ru:'ㄖㄨ',
		rua:'ㄖㄨㄚ',
		ruan:'ㄖㄨㄢ',
		rui:'ㄖㄨㄟ',
		run:'ㄖㄨㄣ',
		ruo:'ㄖㄨㄛ',
		sa:'ㄙㄚ',
		sai:'ㄙㄞ',
		san:'ㄙㄢ',
		sang:'ㄙㄤ',
		sao:'ㄙㄠ',
		se:'ㄙㄜ',
		sen:'ㄙㄣ',
		seng:'ㄙㄥ',
		sha:'ㄕㄚ',
		shai:'ㄕㄞ',
		shan:'ㄕㄢ',
		shang:'ㄕㄤ',
		shao:'ㄕㄠ',
		she:'ㄕㄜ',
		shei:'ㄕㄟ',
		shen:'ㄕㄣ',
		sheng:'ㄕㄥ',
		shi:'ㄕ',
		shou:'ㄕㄡ',
		shu:'ㄕㄨ',
		shua:'ㄕㄨㄚ',
		shuai:'ㄕㄨㄞ',
		shuan:'ㄕㄨㄢ',
		shuang:'ㄕㄨㄤ',
		shui:'ㄕㄨㄟ',
		shun:'ㄕㄨㄣ',
		shuo:'ㄕㄨㄛ',
		si:'ㄙ',
		song:'ㄙㄨㄥ',
		sou:'ㄙㄡ',
		su:'ㄙㄨ',
		suan:'ㄙㄨㄢ',
		sui:'ㄙㄨㄟ',
		sun:'ㄙㄨㄣ',
		suo:'ㄙㄨㄛ',
		ta:'ㄊㄚ',
		tai:'ㄊㄞ',
		tan:'ㄊㄢ',
		tang:'ㄊㄤ',
		tao:'ㄊㄠ',
		te:'ㄊㄜ',
		tei:'ㄊㄟ',
		teng:'ㄊㄥ',
		ti:'ㄊㄧ',
		tian:'ㄊㄧㄢ',
		tiao:'ㄊㄧㄠ',
		tie:'ㄊㄧㄝ',
		ting:'ㄊㄧㄥ',
		tong:'ㄊㄨㄥ',
		tou:'ㄊㄡ',
		tu:'ㄊㄨ',
		tuan:'ㄊㄨㄢ',
		tui:'ㄊㄨㄟ',
		tun:'ㄊㄨㄣ',
		tuo:'ㄊㄨㄛ',
		wa:'ㄨㄚ',
		wai:'ㄨㄞ',
		wan:'ㄨㄢ',
		wang:'ㄨㄤ',
		wei:'ㄨㄟ',
		wen:'ㄨㄣ',
		weng:'ㄨㄥ',
		wo:'ㄨㄛ',
		wu:'ㄨ',
		xi:'ㄒㄧ',
		xia:'ㄒㄧㄚ',
		xian:'ㄒㄧㄢ',
		xiang:'ㄒㄧㄤ',
		xiao:'ㄒㄧㄠ',
		xie:'ㄒㄧㄝ',
		xin:'ㄒㄧㄣ',
		xing:'ㄒㄧㄥ',
		xiong:'ㄒㄩㄥ',
		xiu:'ㄒㄧㄡ',
		xu:'ㄒㄩ',
		xuan:'ㄒㄩㄢ',
		xue:'ㄒㄩㄝ',
		xun:'ㄒㄩㄣ',
		ya:'ㄧㄚ',
		yan:'ㄧㄢ',
		yang:'ㄧㄤ',
		yao:'ㄧㄠ',
		ye:'ㄧㄝ',
		yi:'ㄧ',
		yin:'ㄧㄣ',
		ying:'ㄧㄥ',
		yong:'ㄩㄥ',
		you:'ㄧㄡ',
		yu:'ㄩ',
		yuan:'ㄩㄢ',
		yue:'ㄩㄝ',
		yun:'ㄩㄣ',
		za:'ㄗㄚ',
		zai:'ㄗㄞ',
		zan:'ㄗㄢ',
		zang:'ㄗㄤ',
		zao:'ㄗㄠ',
		ze:'ㄗㄜ',
		zei:'ㄗㄟ',
		zen:'ㄗㄣ',
		zeng:'ㄗㄥ',
		zha:'ㄓㄚ',
		zhai:'ㄓㄞ',
		zhan:'ㄓㄢ',
		zhang:'ㄓㄤ',
		zhao:'ㄓㄠ',
		zhe:'ㄓㄜ',
		zhei:'ㄓㄟ',
		zhen:'ㄓㄣ',
		zheng:'ㄓㄥ',
		zhi:'ㄓ',
		zhong:'ㄓㄨㄥ',
		zhou:'ㄓㄡ',
		zhu:'ㄓㄨ',
		zhua:'ㄓㄨㄚ',
		zhuai:'ㄓㄨㄞ',
		zhuan:'ㄓㄨㄢ',
		zhuang:'ㄓㄨㄤ',
		zhui:'ㄓㄨㄟ',
		zhun:'ㄓㄨㄣ',
		zhuo:'ㄓㄨㄛ',
		zi:'ㄗ',
		zong:'ㄗㄨㄥ',
		zou:'ㄗㄡ',
		zu:'ㄗㄨ',
		zuan:'ㄗㄨㄢ',
		zui:'ㄗㄨㄟ',
		zun:'ㄗㄨㄣ',
		zuo:'ㄗㄨㄛ'
	};

	/* A reference lookup to convert pinyin with a tone into pinyin without */
	var __pinyinToneLookup = {
		'ā':'a1',
		'á':'a2',
		'ǎ':'a3',
		'à':'a4',
		'ē':'e1',
		'é':'e2',
		'ě':'e3',
		'è':'e4',
		'ō':'o1',
		'ó':'o2',
		'ǒ':'o3',
		'ò':'o4',
		'ī':'i1',
		'í':'i2',
		'ǐ':'i3',
		'ì':'i4',
		'ū':'u1',
		'ú':'u2',
		'ǔ':'u3',
		'ù':'u4',
		'ü':'v1',
		'ǘ':'v2',
		'ǚ':'v3',
		'ǜ':'v4',
		'ń':'n2',
		'ň':'n3',
		'':'m2'
	}

	/* The possible tones to use while rendering zhuyin. */
	var __zhuyinTones = '  ˊˇˋ˙';

	/* A list of chinese symbols that we have no intention of trying to write pinyin or zhuyin for. */
	var __chineseGrammarTokens = '，。 《》／？ ；「：『」』';

	/* A list of chinese symbols that we have no intention of trying to write pinyin or zhuyin for. */
	var __chineseGrammarTokens = '，。 《》／？ ；「：『」』';

	/* Lookup pinyin tone. Use the lookup to find a friendly character for the pinyin and a tone number
	 * for the programmer.
	 */
	var getPinyinTone = function(input) {
		for (var pinyin in __pinyinToneLookup) {
			if (input.indexOf(pinyin) > -1) {
				var tone = __pinyinToneLookup[pinyin].split('');
				return [
					input.replace(pinyin, tone[0]),
					parseInt(tone[1])
				];
			}
		}
		// if it's not found in the lookup table, then it must be a first flat tone,, which is often not
		// 	included in the written form of pinyin when using shorthand.
		return [input, 1];
	}


	/* Accepts an array of, or string of space separated pinyin strings, to be converted into the
	 * zhuyin equivalants.
	 * Returns: an array of zhuyin strings for each respective pinyin input
	 * Example:
	 * 	console.log(pinyinToZhuyin(["zhū", "niú", "jī", "yáng"]));
	 * 	>> [["ㄓㄨ","1"],["ㄋㄧㄡ","2"],["ㄐㄧ","1"],["ㄧㄤ","2"]]
	 */
	export default function pinyinToZhuyin(input) {
		var payload;
		// ensure our working payload is in array from
		if (typeof input == 'string') {
			payload = input.split(' ');
		} else {
			payload = input;
		}
		// now start processing input
		// __pinyinToZhuyinLookup     __pinyinToneLookup
		var output = [];
		for (var i = 0; i < payload.length; i++) {
			var tone = getPinyinTone(payload[i]);
			var zhuyin = __pinyinToZhuyinLookup[tone[0]];
			if (zhuyin == undefined)
				zhuyin = null;
			output.push([zhuyin, __zhuyinTones[tone[1]]]);
		}
		// return to caller
		return output;
	}
